export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A 3D-printed armchair in the shape of a ripe avocado, with soft, textured green upholstery",
  "A surrealistic, dream-like oil painting by Salvador Dalí featuring a whimsical cat playing checkers on a floating chessboard in a cosmic landscape",
  "Teddy bears dressed in traditional Japanese attire, elegantly shopping for groceries in a bustling ukiyo-e woodblock print",
  "An oil painting by Matisse depicting a lifelike humanoid robot engaged in an intense game of chess against a human opponent, with intricate metallic details",
  "A digital art composition of a mischievous panda, dressed as a mad scientist, conducting a symphony of sparkling, neon-colored chemicals in a lab of wonder",
  "A highly detailed 3D-rendered macro photograph captured with a 35mm lens, showcasing two adorable mice in Hawaii, each donning miniature swimsuits and carrying tiny surfboards",
  "A mesmerizing 3D render of a vibrant tropical fish gracefully swimming in an impeccably designed aquarium, set against a deep, inky blue background",
  "An astronaut, exquisitely depicted in a vaporwave-inspired digital artwork, leisurely lounging in a futuristic tropical resort amid the cosmos",
  "An oil painting portrait of a regal capybara adorned in opulent medieval royal robes and an ornate crown, set against a mysterious, dark backdrop",
  "A captivating stained glass window art piece portraying a mouthwatering hamburger and a generous serving of golden french fries, glowing with radiant colors",
  "A meticulously detailed pencil and watercolor drawing, envisioning a bustling, futuristic cityscape filled with sleek flying cars soaring amidst towering skyscrapers",
  "A digital art creation showcasing a sunlit indoor lounge area with two inviting pools - one with crystal-clear water and the other with translucent pastel-pink water, framed by a colossal window",
  "An intriguing digital art piece featuring a fortune-telling Shiba Inu, peering into a colossal hamburger to unveil the secrets of your destiny",
  'A whimsical reimagining of Johannes Vermeer\'s "Girl with a Pearl Earring," featuring a sea otter adorned with a resplendent pearl earring',
  "An expressive oil pastel drawing capturing the vexed countenance of a feline adventurer exploring the cosmos within the confines of a futuristic spaceship",
  'A stunning painting fusing the style of Vincent van Gogh\'s "Starry Night" with a majestic fox as the central figure, set against a mesmerizing, star-studded sky',
  "A charming knitted art creation resembling a bowl of soup, playfully designed to look like a friendly and slightly mischievous monster",
  "A plush toy robot, meticulously crafted to resemble a sleek, futuristic automaton, peacefully sitting against a vibrant yellow wall",
  "A mesmerizing digital art piece showcasing a synthwave-inspired sunset casting vibrant hues of neon and magenta over the tranquil waters of the sea",
  "A visionary 3D render capturing two futuristic towers connected by a lush skybridge, enveloped in a vibrant tapestry of vibrant foliage and cascading waterfalls",
  "A breathtaking 3D render featuring a rainbow-colored hot air balloon soaring gracefully above a mirror-like lake, with reflections that appear almost magical",
  "An eye-catching comic book cover depicting a superhero donning headphones, ready to embark on an epic audio-powered adventure",
  "A captivating photograph capturing the explosive moment of colorful powder dispersing in a perfectly centered explosion against a pitch-black background",
  "A heartwarming photo of a fluffy Samoyed dog, tongue playfully out, sharing an affectionate hug with a white Siamese cat",
  "An otherworldly photograph capturing a mysterious white fur monster standing in a room awash with deep, enigmatic shades of purple",
  "A playful photograph of Michelangelo's iconic sculpture of David, humorously reimagined with the statue wearing headphones and spinning tracks as a DJ",
  "A captivating lomography shot of a Samurai astride a majestic horse, set against the otherworldly backdrop of Mars",
  "A modern, sleek Cadillac cruising along the scenic Gardiner Expressway in Toronto, with the bustling downtown skyline in the background and a dazzling lens flare accentuating the scene",
  "A stunningly realistic photograph showcasing a young woman with mesmerizing blue eyes and flowing blonde hair, creating an enchanting aura",
  "A mysterious photograph capturing a man standing in front of a swirling stargate, seemingly on the brink of a journey to another dimension",
  "A whimsical crossover of Spongebob Squarepants in the eerie and suspenseful atmosphere of the Blair Witch Project",
  "A charming lomography shot capturing a velociraptor expertly serving hotdogs from a vibrant and nostalgic hotdog stand",
  "A captivating 50mm lens photograph of a man navigating the vibrant and neon-lit streets of Kowloon during a bustling night",
  "A heartwarming digital art creation portraying a lively barbecue grill, anthropomorphized and brought to life in the delightful style of a Pixar animated movie",
  "An electrifying digital art depiction of a futuristic cyborg dance club illuminated by pulsating neon lights, where humans and machines unite in a symphony of movement",
  "A captivating glimpse into an alternate universe with the long-lost Star Wars 1990 Japanese Anime, where iconic characters and epic battles take on a unique anime-style twist",
  "A mouthwatering professional food photograph presenting a hamburger ingeniously crafted into the form of a Rubik’s cube, showcasing culinary artistry",
  "A synthwave-inspired artwork featuring a futuristic hedgehog, traversing a Blade Runner-inspired cyberpunk cityscape, bathed in neon ambiance",
  "An awe-inspiring photograph capturing the moment an astronaut encounters a mesmerizing alien life form on a distant and enigmatic planet",
  "A breathtaking photograph capturing a dinosaur embarking on an adventurous exploration of the picturesque landscapes of Cape Town",
  "A captivating digital art piece narrating a tale of love as a man falls head over heels for his computer, in a world where technology and emotion intertwine",
  "A stunning lomography photograph capturing a cyborg's nocturnal exploration of Tokyo's futuristic streets, brilliantly illuminated by neon lights",
  "A captivating black and white photograph portraying Dracula, the iconic vampire, strolling down the historic streets of New York City in the glamorous 1920s era",
  "An exhilarating digital art creation featuring a sleek synthwave aeroplane soaring through a mesmerizing cyberpunk skyline",
  "A mesmerizing 50mm lens photograph of a man wandering through the enchanting, rain-soaked streets of Tokyo, where bright neon signs create a surreal, otherworldly atmosphere",
  "A captivating digital art composition depicting a Space Shuttle majestically soaring above the scenic landscapes of Cape Town, against a backdrop of cosmic beauty",
];
